trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  name: 'AgentPool-Ubuntu-H01'

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '10.x'

  - script: |
      docker info
    displayName: 'Verify Docker is available'

  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Run Build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--no-restore'

  - task: DotNetCoreCLI@2
      displayName: Trust Dev Certs
      inputs:
        command: custom
        custom: dev-certs
        arguments: https --trust
        env:
          SSL_CERT_DIR: '$(HOME)/.aspnet/dev-certs/trust'

  - task: DotNetCoreCLI@2
    displayName: 'Run Integration Tests'
    inputs:
      command: 'test'
      projects: '**/EmployeeManagement.IntegrationTest.csproj'
      arguments: '--no-build -v diag'

  - task: PublishTestResults@2
    displayName: 'Publish Integration Test Results'
    condition: always()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(Agent.TempDirectory)/TestResults/*.trx'
